### ISSUE TITLE
src\main\kotlin\de.jjohannes.javamodules.java.gradle.kts: (17, 13): Unresolved reference: release

### ISSUE THREAD

**Issue by elect86** [jjohannes/gradle-jpms-experiments#2]
As titled

```
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:configurePrecompiledScriptDependenciesResolver
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE

> Task :buildSrc:compileKotlin FAILED
The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.4-rc-1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
e: C:\Users\gbarbieri\IdeaProjects\gradle-jpms-experiments\buildSrc\src\main\kotlin\de.jjohannes.javamodules.java.gradle.kts: (17, 13): Unresolved reference: release

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


```

**Comment by jjohannes** [comment]
You need Gradle 6.7+ to run the current master version of the sample. You may use the wrapper of the sample: `./gradlew build`.

I updated the README to state this.

**Comment by elect86** [comment]
Shouldn't be already using 6.7 (as stated [here](https://github.com/jjohannes/gradle-jpms-experiments/blob/master/gradle/wrapper/gradle-wrapper.properties#L3))?

**Comment by jjohannes** [comment]
Yes it does and it works for me. The message you posted above indicates that you ran the build with `6.4-rc-1` there (see documentation link in the output).

**Comment by elect86** [comment]
How can it pick 6.4-rc-1 instead of the one specified by the wrapper?
